### ISSUE TITLE
Upgrade to 1.9.2.4

### ISSUE THREAD

**Issue by qsolutions-pl** [mercator/mercator#15]
Hi guys, do you plan to do the upgrade to 1.9.2.4?

**Comment by gfxguru** [comment]
that's a very good question

**Comment by lloydhazlett** [comment]
@gfxguru I was hoping you might be interested in the project, thanks for taking the time to check it out!

Unfortunately we haven't put out updates for the last 5 Magento 1 releases, which is due to the general lack of interest up to this point. And with the release of Magento 2, we're expecting that gaining any traction will now be even harder. When we started the project we hoped to be able to get some other contributors on board (ideally maintainers of the included extensions), but this hasn't eventuated.

We'll update to 1.9.2.4 shortly, and we would then welcome any feedback on the mercator distribution in its current state and the project in general. If anyone wants to get involved, please jump in. We will need wider participation for this project to continue long term.

**Comment by QSolutionsStudio** [comment]
We do have few projects already launched on Mercator already, for example http://yes.pl runs on it. We even created a new admin interface for entire Magento1 giving it a whole new look and responsive SVG charts for reporting. Check it out:
http://screencast.com/t/8NPxequgB
http://screencast.com/t/3oWuLgPRTw

**Comment by lloydhazlett** [comment]
We've now merged the upstream [1.9.2.4](https://github.com/mercator/mercator/commit/82d97b12f5fa42167234d4840d41aa22b8281aa5) changes. Would be good to get some more feedback, so if you try it out then please let us know what you think.

@QSolutionsStudio That's great to hear, glad it's been useful for those projects. The admin panel theme and charts look interesting, are they extensions you've released?

**Comment by QSolutionsStudio** [comment]
I will give it a try later this evening, have to finish some tasks for a client today. As for the admin theme and charts, we plan to release them to community with our new website - which is this weekend.
