### ISSUE TITLE
Upgrade to 1.9.3.3

### ISSUE THREAD

**Issue by posttechguy** [mercator/mercator#17]
Hi,

I wanted to get an ETA for the upgrades, specifically Magento 1.9.3.3 SUPEE-9767 patch security updates.

Thanks for your work

Bevan

**Comment by chnorton** [comment]
Unfortunately there hasn't been a lot of interest in the project so we're unlikely to be making any further updates at this point. A project of this nature is obviously a large undertaking, and without finding other contributors and potential maintainers we will need to leave it on hold. We are more than happy to accept PRs though, or let us know if you'd be interested in becoming more involved with the project in any other way.

In terms of the patches, due to the underlying code still being Magento, it is possible to apply security patches cleanly in most cases so the process shouldn't be any different than a normal Magento site.
