### ISSUE TITLE
Magento Security patches?

### ISSUE THREAD

**Issue by qsolutions-pl** [mercator/mercator#8]
Hi guys, have you install lastest 2 magento security patches?

**Comment by chnorton** [comment]
We haven't applied the patches to the Mercator base yet as we were waiting for Magento to release the new version of CE and bring it up to date with EE 1.14.2.0, thinking that this would have happened right after the EE release. Given that it's been almost two months, we'll just go ahead and apply them now so that everyone doesn't have to keep doing it manually. Expect an update shortly.
